cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --export=PATH
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=short
  - mem_mb=1000
restart-times: 1
max-jobs-per-second: 0.01
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-status: status-sacct.sh
cluster-cancel: scancel
